name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.local/bin:$PATH"

    - name: Install dependencies
      run: |
        poetry install
        poetry self add poetry-dynamic-versioning

    - name: Set up Poetry token
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Build and Publish to PyPI
      env:
        POETRY_DYNAMIC_VERSIONING_ENABLE: true  # Ensures dynamic versioning is enabled
      run: |
        poetry publish --build
